language: ruby
rvm:
  - 2.5.1

# addons:
#   firefox: "65.0.2"

# before_install:
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3
# before_install:
#   - gem install bundler -v '>=1.16.6'
# script:
  # - bundle exec rails db:migrate RAILS_ENV=test
  # - bundle exec rspec