x-default_env: &env
  environment:
    - NODE_ENV=development
    - RAILS_ENV=development
    - DATABASE_URL=postgres://root@db:5432
    - BUNDLE_PATH=/gems
    - GEM_PATH=/gems
    - GEM_HOME=/gems
    - PATH=/usr/local/bundle/bin:/usr/local/bundle/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/gems/bin
    - WEBPACKER_DEV_SERVER_HOST=sh
version: '3.4'
services:
  db:
    image: postgres:10-alpine
    environment:
      - POSTGRES_USER=root
    volumes:
      - postgres-vol:/var/lib/postgresql/data
  spring:
    build: .
    volumes:
      - .:/app
      - spring-vol:/spring
      - gems:/gems
    command: spring server
    environment:
      - DATABASE_URL=postgres://root@db:5432
      - SPRING_TMP_PATH=/spring
      - GEM_PATH=/gems
      - GEM_HOME=/gems
      - PATH=/usr/local/bundle/bin:/usr/local/bundle/gems/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/gems/bin
    pid: host
  web:
    build: .
    command: unbuffer bundle exec rails s -p 1337 -b '0.0.0.0'
    <<: *env
    volumes:
      - .:/app
      - spring-vol:/spring
      - gems:/gems
    ports:
      - "1337:1337"
    depends_on:
      - db
      - spring
      # Uncomment this line if you'd like to enable Webpack Dev Server
      # - sh
  sh:
    build: .
    command: ./bin/webpack-dev-server
    <<: *env
    volumes:
      - .:/app
      - spring-vol:/spring
      - gems:/gems
    ports:
      - "3035:3035" # for Webpack Dev Server, if run from sh
volumes:
  spring-vol:
  postgres-vol:
  gems:
